[toolchain]

[features]
resolution = true
skip-lint = false

[programs.testnet]
testore_program = "TESTORE11111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
