[workspace]
members = [
    "cli",
    "bridge",
    "programs/testore-program",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["TestORE Contributors"]
repository = "https://github.com/your-username/testore"
homepage = "https://github.com/your-username/testore"
description = "Solana testnet stress testing miner with mainnet airdrops"

[workspace.dependencies]
# Solana Core
solana-sdk = "~1.18"
solana-client = "~1.18"
solana-program = "~1.18"
solana-cli-config = "~1.18"

# Anchor Framework
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"

# Crypto & Hashing
sha3 = "0.10"
bs58 = "0.5"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# CLI & Async
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"

# Terminal UI
colored = "2.1"
indicatif = "0.17"

# Logging
env_logger = "0.11"
log = "0.4"

# Concurrency
rayon = "1.8"
num_cpus = "1.16"

# Additional
chrono = "0.4"
